# Generated by Django 5.0.6 on 2024-06-12 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('mode', models.CharField(choices=[('ROBOT', 'ROBOT'), ('USER', 'USER')], default='USER', max_length=10)),
                ('stocks_collection_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investment',
                'db_table': 'Investment',
                'ordering': ['-id'],
            },
        ),
    ]
