# Generated by Django 5.0.6 on 2024-06-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.investoruser'),
        ),
    ]
