# Generated by Django 5.0.2 on 2024-06-10 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
        ('users', '0002_customuser_investoruser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.investoruser'),
        ),
    ]
